name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Set build environment vars
        shell: bash
        run: |
          echo "NEXT_PUBLIC_VERSION=$(node -p "require('./package.json').version || '0.1.0'")" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_GIT_SHA=${{ github.sha }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_BUILT_AT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm ci

      - name: Lint (if available)
        shell: bash
        run: |
          if node -e "const s=require('./package.json').scripts||{}; process.exit(s.lint?0:1)"; then
            npm run lint
          else
            echo "No lint script defined; skipping."
          fi

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

